# Generated by Django 5.2.8 on 2025-11-13 08:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Batch",
            fields=[
                (
                    "deleted",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this record",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time when this record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when this record was last updated",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this record is active"
                    ),
                ),
                ("date", models.DateField(help_text="Date of the batch")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Passport",
            fields=[
                (
                    "deleted",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this record",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time when this record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when this record was last updated",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this record is active"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Unique code for the passport",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "coupon_id",
                    models.CharField(
                        help_text="Coupon identifier associated with the passport",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        help_text="First name of the passport holder", max_length=100
                    ),
                ),
                (
                    "middle_name",
                    models.CharField(
                        blank=True,
                        help_text="Middle name of the passport holder",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        help_text="Last name of the passport holder", max_length=100
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        help_text="Gender of the passport holder", max_length=10
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("published", "Published"),
                            ("draft", "Draft"),
                            ("lost", "Lost"),
                            ("taken", "Taken"),
                        ],
                        default="draft",
                        help_text="Status of the passport",
                        max_length=50,
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Publication date of the passport",
                        null=True,
                    ),
                ),
                (
                    "taken_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date when the passport was taken",
                        null=True,
                    ),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        help_text="The batch this passport belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="passports",
                        to="passport.batch",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
