# Generated by Django 5.2.8 on 2025-11-22 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("passport", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="batch",
            options={
                "verbose_name": "Lot des passports",
                "verbose_name_plural": "Lots des passports",
            },
        ),
        migrations.AlterModelOptions(
            name="passport",
            options={"verbose_name": "Passport", "verbose_name_plural": "Passports"},
        ),
        migrations.AlterField(
            model_name="batch",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Date and time when this record was created",
                verbose_name="Date de creation",
            ),
        ),
        migrations.AlterField(
            model_name="batch",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Whether this record is active",
                verbose_name="Est actif",
            ),
        ),
        migrations.AlterField(
            model_name="batch",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "En attente"),
                    ("received", "Reçu"),
                    ("processing", "En traitement"),
                    ("completed", "Terminé"),
                    ("published", "Publié"),
                ],
                default="pending",
                help_text="Status of the batch",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="batch",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Date and time when this record was last updated",
                verbose_name="Date de modification",
            ),
        ),
        migrations.AlterField(
            model_name="passport",
            name="batch",
            field=models.ForeignKey(
                help_text="The batch this passport belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="passports",
                to="passport.batch",
                verbose_name="Lot",
            ),
        ),
        migrations.AlterField(
            model_name="passport",
            name="code",
            field=models.CharField(
                blank=True,
                help_text="Unique code for the passport",
                max_length=100,
                unique=True,
                verbose_name="Code du Passport",
            ),
        ),
        migrations.AlterField(
            model_name="passport",
            name="coupon_id",
            field=models.CharField(
                blank=True,
                help_text="Coupon identifier associated with the passport",
                max_length=100,
                unique=True,
                verbose_name="ID du Coupon",
            ),
        ),
        migrations.AlterField(
            model_name="passport",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Date and time when this record was created",
                verbose_name="Date de creation",
            ),
        ),
        migrations.AlterField(
            model_name="passport",
            name="first_name",
            field=models.CharField(
                help_text="First name of the passport holder",
                max_length=100,
                verbose_name="Prénom",
            ),
        ),
        migrations.AlterField(
            model_name="passport",
            name="gender",
            field=models.CharField(
                help_text="Gender of the passport holder",
                max_length=10,
                verbose_name="Genre",
            ),
        ),
        migrations.AlterField(
            model_name="passport",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Whether this record is active",
                verbose_name="Est actif",
            ),
        ),
        migrations.AlterField(
            model_name="passport",
            name="last_name",
            field=models.CharField(
                help_text="Last name of the passport holder",
                max_length=100,
                verbose_name="Nom",
            ),
        ),
        migrations.AlterField(
            model_name="passport",
            name="middle_name",
            field=models.CharField(
                blank=True,
                help_text="Middle name of the passport holder",
                max_length=100,
                null=True,
                verbose_name="Postnom",
            ),
        ),
        migrations.AlterField(
            model_name="passport",
            name="published_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Publication date of the passport",
                null=True,
                verbose_name="Date de Publication",
            ),
        ),
        migrations.AlterField(
            model_name="passport",
            name="status",
            field=models.CharField(
                choices=[
                    ("published", "Publié"),
                    ("draft", "Brouillon"),
                    ("completed", "Terminé"),
                    ("lost", "Perdu"),
                    ("taken", "Retiré"),
                ],
                default="draft",
                help_text="Status of the passport",
                max_length=50,
                verbose_name="Statut",
            ),
        ),
        migrations.AlterField(
            model_name="passport",
            name="taken_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Date when the passport was taken",
                null=True,
                verbose_name="Date de Retrait",
            ),
        ),
        migrations.AlterField(
            model_name="passport",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Date and time when this record was last updated",
                verbose_name="Date de modification",
            ),
        ),
    ]
