# Generated by Django 5.2.8 on 2025-11-13 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("passport", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="batch",
            old_name="date",
            new_name="received_date",
        ),
    ]
