# Generated by Django 5.2.8 on 2025-11-13 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("passport", "0002_rename_date_batch_received_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="batch",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("received", "Received"),
                    ("processing", "Processing"),
                    ("completed", "Completed"),
                ],
                default="pending",
                help_text="Status of the batch",
                max_length=50,
            ),
        ),
    ]
