# Generated by Django 5.2.8 on 2025-11-22 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("passport", "0002_alter_batch_options_alter_passport_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="batch",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="passport",
            name="is_active",
        ),
        migrations.AlterField(
            model_name="passport",
            name="code",
            field=models.CharField(
                blank=True,
                help_text="Unique code for the passport",
                max_length=100,
                unique=True,
                verbose_name="Code du dassport",
            ),
        ),
        migrations.AlterField(
            model_name="passport",
            name="coupon_id",
            field=models.CharField(
                blank=True,
                help_text="Coupon identifier associated with the passport",
                max_length=100,
                unique=True,
                verbose_name="ID du coupon",
            ),
        ),
        migrations.AlterField(
            model_name="passport",
            name="published_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Publication date of the passport",
                null=True,
                verbose_name="Date de publication",
            ),
        ),
        migrations.AlterField(
            model_name="passport",
            name="taken_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Date when the passport was taken",
                null=True,
                verbose_name="Date de retrait",
            ),
        ),
    ]
