# Generated by Django 5.2.8 on 2025-11-22 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("passport", "0003_remove_batch_is_active_remove_passport_is_active_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="passport",
            name="gender",
            field=models.CharField(
                choices=[("male", "Homme"), ("female", "Femme")],
                help_text="Gender of the passport holder",
                max_length=10,
                verbose_name="Genre",
            ),
        ),
    ]
