# Generated by Django 5.2.8 on 2025-11-14 14:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organisations", "0002_remove_organization_website"),
        ("passport", "0003_batch_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="batch",
            name="organization",
            field=models.ForeignKey(
                help_text="The organization this batch belongs to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="batches",
                to="organisations.organization",
            ),
        ),
        migrations.AlterField(
            model_name="batch",
            name="received_date",
            field=models.DateField(
                default=django.utils.timezone.now, help_text="Date of the batch"
            ),
        ),
        migrations.AlterField(
            model_name="batch",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("received", "Received"),
                    ("processing", "Processing"),
                    ("completed", "Completed"),
                    ("published", "Published"),
                ],
                default="pending",
                help_text="Status of the batch",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="passport",
            name="status",
            field=models.CharField(
                choices=[
                    ("published", "Published"),
                    ("draft", "Draft"),
                    ("completed", "Completed"),
                    ("lost", "Lost"),
                    ("taken", "Taken"),
                ],
                default="draft",
                help_text="Status of the passport",
                max_length=50,
            ),
        ),
    ]
