# Generated by Django 5.2.8 on 2025-11-22 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("passport", "0004_alter_passport_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="passport",
            name="code",
            field=models.CharField(
                blank=True,
                help_text="Unique code for the passport",
                max_length=100,
                unique=True,
                verbose_name="Code du passport",
            ),
        ),
        migrations.AlterField(
            model_name="passport",
            name="published_at",
            field=models.DateField(
                blank=True,
                help_text="Publication date of the passport",
                null=True,
                verbose_name="Date de publication",
            ),
        ),
        migrations.AlterField(
            model_name="passport",
            name="taken_at",
            field=models.DateField(
                blank=True,
                help_text="Date when the passport was taken",
                null=True,
                verbose_name="Date de retrait",
            ),
        ),
    ]
