# Generated by Django 5.2.8 on 2025-11-12 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organisations", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organization",
            name="website",
        ),
    ]
