# Generated by Django 5.2.8 on 2025-11-22 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organisations", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="organizationuser",
            options={
                "verbose_name": "Utilisateur de l'organisation",
                "verbose_name_plural": "Utilisateurs de l'organisation",
            },
        ),
        migrations.AlterField(
            model_name="organization",
            name="email",
            field=models.EmailField(
                blank=True,
                help_text="Email de contact principal",
                max_length=254,
                null=True,
                verbose_name="dmail",
            ),
        ),
        migrations.AlterField(
            model_name="organizationuser",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Whether this record is active",
                verbose_name="Est actif",
            ),
        ),
    ]
